ARG PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# ------------------------------
# Development Docker Image
# ------------------------------
# This image includes development dependencies and testing tools
FROM node:22-bookworm-slim AS dev

ARG PLAYWRIGHT_BROWSERS_PATH
ENV PLAYWRIGHT_BROWSERS_PATH=${PLAYWRIGHT_BROWSERS_PATH}

# Set the working directory
WORKDIR /app

# Install system dependencies first
RUN --mount=type=cache,target=/root/.npm,sharing=locked,id=npm-cache \
    --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
  npm ci && \
  # Install system dependencies for playwright
  npx -y playwright-core install-deps chromium

# Copy the rest of the app
COPY *.json *.js *.ts .
COPY src src/
COPY tests tests/
COPY utils utils/

# Build the app
RUN npm run build

# Install chromium browser
RUN npx -y playwright-core install --no-shell chromium

# Run in headless and only with chromium (other browsers need more dependencies not included in this image)
ENTRYPOINT ["node", "cli.js", "--headless", "--browser", "chromium", "--no-sandbox"]